[package]
name = "neural_network"
version = "0.1.0"
authors = ["Le Duyen Sandra Vu <leduvu@gmail.com>"]

[dependencies]
approx = "0.2"
ndarray = "0.11"
ndarray-rand = "0.7.0"
rand = "0.4"
stdinout = "0.4"
failure = "0.1"
clap = "2"
float-cmp = "0.4.0"